### ISSUE TITLE
Accuracy Thresholds in Open

### ISSUE THREAD

**Issue by DilipSequeira** [mlperf/inference_policies#131]
Today there are no accuracy restrictions in Open, which in combination with accuracy not being in the results table allows for submissions that are bad both for comparability and MLPerf's credibility.

Proposals

(a) a tag for open division (similar to the "structured retraining" tag) that is "meets_accuracy" for models which meet the closed accuracy threshold (or more specific, if we have two thresholds in Closed)

(b) Change 

_Latency and accuracy constraints are not applicable: instead the submission must report the accuracy obtained, and the latency constraints under which the reported performance was obtained._

to 

_Latency constraints are not applicable: instead the submission must report the latency constraints under which the reported performance was obtained. Accuracy must meet the Open Accuracy target for the benchmark, and the submission must report the accuracy obtained_

Where Open Accuracy is a threshold for each benchmark that is liberal enough to capture all interesting submissions (this would be determined by the Advisory Groups, or proposed by model owners and vetted by the working group where Advisory Groups do not yet exist.)

**Comment by tjablin** [comment]
I think the proposal for a tag is very reasonable. If we are going to have a tag for Open submissions meeting the accuracy target, should we also have a tag for Open submissions meeting the latency target? I'd prefer having one accuracy target and one latency target per benchmark rather than having separate targets for Open and Closed. I think having two different targets will be confusing for the press. Also, setting accuracy targets has been contentious in the past, I am concerned that twice as many targets will be twice as contentious.

In regards to part b of the proposal, I would prefer not to outright ban any implementation from open. Maybe ultra-low accuracy, low-power, high-performance is interesting to someone?

**Comment by DilipSequeira** [comment]
A latency tag sounds fine to me.

For part b... open should allow any accuracy a reasonable person might find interesting in a submission, given certain other properties - and we should err on the side of liberality. Absent the advisory groups, we could e.g. just take the minimum of what anyone in the working group thinks makes sense.

**Comment by christ1ne** [comment]
updated the latest rules about the open category. Please reopen if needed. https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#412-relaxed-constraints-for-the-open-division
