### ISSUE TITLE
update server scenario wording for DLRM

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#137]
Please suggest some wording to update the section:https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#3-scenarios
right now the server scenario has 1 sample per query (end of the section)

@mnaumovfb

Many thanks!

**Comment by mnaumovfb** [comment]
In the case of DLRM we have agreed that we should use multiple samples drawn from a distribution, similar to the one shown on Fig. 5: "Queries for personalized recommendation models" in the [DeepRecSys paper](https://arxiv.org/abs/2001.02772). 

I would add the following background and specifications about it. 
"The DLRM MLPerf inference code has an option to aggregate multiple consecutive samples together into a single aggregated sample. The number of samples to be aggregated can be selected using either of the following options 
(i) fixed [`--samples-to-aggregate-fix`]
(ii) drawn uniformly from interval [`--samples-to-aggregate-min`, `--samples-to-aggregate-max`]
(iii) drawn from a custom distribution, with its quantile (inverse of CDP) specified in `--samples-to-aggregate-quantile-file=./tools/dist_quantile.txt`. 

The benchmark provides a pre-defined quantile distribution in `./tools/dist_quantile.txt` from which the samples will be drawn using the inverse transform algorithm. This algorithm relies on randomly drawn numbers from the interval [0,1) and that depend on the `--numpy-rand-seed`, which specific value will be provided shortly before MLPerf inference submissions. 

In order to eliminate the discrepancy between different number generators, the submitters can verify their compatibility by using the default `--numpy-rand-seed` and comparing the trace generated on their system with `tools/dist_trace_verification.txt` using the following command 
```
./run_local.sh pytorch dlrm terabyte cpu --count-samples=100 --scenario Offline --max-ind-range=40000000 --samples-to-aggregate-quantile-file=./tools/dist_quantile.txt --max-batchsize=128
```

Therefore, the command to run the Server scenario should be something like
```
./run_local.sh pytorch dlrm terabyte cpu --scenario Server --max-ind-range=40000000 --samples-to-aggregate-quantile-file=./tools/dist_quantile.txt
```
"

Let me know if this helps.

**Comment by christ1ne** [comment]
@christ1ne  to follow up

list the definition for samples in the rules.

DLRM: each sample can map up to 700 user-item pairs with custom distribution defined above.

**Comment by christ1ne** [comment]
PR updated. @mnaumovfb
