### ISSUE TITLE
same SW or different SW allowed for different scenarios?

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#140]

**Comment by galv** [comment]
Original email thread: https://groups.google.com/d/msg/mlperf-inference-submitters/ZG7OxoTsR1E/w10yfu-lBAAJ

@TheKanter  brought up the question "What about changing RTL in FPGAs? Seems like it should be allowed."

My gut instinct tells me that, yes, changing software (including RTL) for different scenarios should be allowed. People who have programmed accelerators for a while have probably noticed that it is common to hardcode specific parameters for your workload in your software. A common mechanism for doing this is C++ templates. It is common to hardcode parameters like max sequence length and batch size  in TPUs, IPUs, FPGAs, etc. because it allows for you to know statically the memory usage of your design, which is required in some cases for the model to be run at all (by selecting an implementation that uses little scratch space, for example. Those familiar with all the ways to implement convolution should know what I mean). In fact, it is necessary to hardcode these parameters, in the case of FPGAs.

Let's consider GPUs because they are probably familiar to most. Consider RNN models. In the _SingleStream scenario_, there is no little latency hiding, so it is natural to use Persistent RNNs. Then consider the _Offline scenario_, since you can use a very large batch size, you probably want to use a GEMM-based RNN implementation instead (persistent RNNs, at least in the NVIDIA Maxwell architecture era, have a maximum batch size of 4, so they are poorly suited to large batches).

It's not clear to me where the cutoff is if you wanted to place restrictions on software, or how you could police this. If you look at cudnn, it essentially has a bunch of persistent RNN templates that have been explicitly instantiated, and if you have the right parameters like sequence length, batch size, etc., one of them will be picked. So it is conceivable that a submitter could just have an "if" statement that chooses the correctly tuned model in their software stack. If you were using FPGAs, think of this as the host software dynamically loading a different bitstream at runtime, but all bitstreams are precompiled. My understanding is that submissions have to be "open source" (I am still new here), but many of these vendor-accelerated libraries are binary blobs (like cudnn). So that is why software restrictions seem hard to police.

**Comment by TheKanter** [comment]
WG agrees that different implementations of models for different scenarios is allowed based on rules about different implementations for different inputs. Will update rules accordingly.
