### ISSUE TITLE
update the rules with accuracy represented 3 digits after decimal

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#38]

**Comment by psyhtest** [comment]
See https://github.com/mlperf/inference/issues/293 and https://github.com/mlperf/inference/pull/320.

**Comment by jveejay** [comment]
@tjablin can you please update the rules doc to state that the accuracy should be provided with 5-bit accuracy? 

@psyhtest can you please update https://github.com/mlperf/inference/tree/master/v0.5/classification_and_detection with the latest accuracy results? mAP is not up to max precision. Can you update and issue a PR, plz?

**Comment by tjablin** [comment]
[PR44](https://github.com/mlperf/inference_policies/pull/44) should resolve. PTAL.

**Comment by psyhtest** [comment]
Here's a PR for image classification: https://github.com/mlperf/inference/pull/341. TFLite MobileNet figures are [from CK](https://github.com/mlperf/inference/tree/master/v0.5/classification_and_detection/optional_harness_ck/classification/tflite#accuracy) due to https://github.com/mlperf/inference/issues/334.

At the moment, https://github.com/mlperf/inference/issues/329 is in the way of obtaining reference mAP for object detection.

**Comment by christ1ne** [comment]
addressed.
