### ISSUE TITLE
can we 'borrow' calibration techniques during the review period

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#98]
As training is not a HP tuning contest and we allow 'HP borrowing' post submission, and inference should not be a calibration contest either, do we allow 'calibration borrowing' during the review period?

**Comment by tjablin** [comment]
There are a lot of techniques that improve performance for the MLPerf 0.5 models that are not architecture specific. It is very unlikely that any submitter has thought of or implemented all of them. Consequently, it is very likely that all submitter could be in the slightly awkward position of being able to submit better numbers after inspecting other submissions. In a perfect world, maybe we would iterate to convergence, but in order to make our commitments on auditing and publication, I don't think there's any time for a 'HP borrowing' round. Even for something as 'simple' as calibration.

I think for MLPerf Inference 0.6, I would be in favor for having some sort of technique borrowing round, but I believe that Peter opposes it, but it is hard to administer. For Inference, I think that many techniques are architecture independent and we are all developing independently a lot of basically identical infrastructure. Next time, it might make sense for one or more submitters to form an alliance to share infrastructure and architecture independent improvements in order to reduce the per submitter burden. I think per submitter burden is one of the major problems with MLPerf.

**Comment by tjablin** [comment]
WG decides no borrowing.
